# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCC <- function(a, b, n, m, X1) {
    .Call('_StatComp21005_CCC', PACKAGE = 'StatComp21005', a, b, n, m, X1)
}

